export type CardCategory = 'statistics' | 'functional' | 'dashboard-cards' | 'dashboard-charts';

export interface CardConfig {
  id: string;
  name: string;
  description: string;
  category: CardCategory;
  icon?: string;
  defaultWidth?: number;
  defaultHeight?: number;
}

export const AVAILABLE_STAT_CARDS: CardConfig[] = [
  {
    id: 'stat-total',
    name: 'Total no Mês',
    description: 'Total de sessões no mês atual',
    category: 'statistics',
    defaultWidth: 200,
    defaultHeight: 120,
  },
  {
    id: 'stat-attended',
    name: 'Comparecidas',
    description: 'Sessões comparecidas no mês',
    category: 'statistics',
    defaultWidth: 200,
    defaultHeight: 120,
  },
  {
    id: 'stat-scheduled',
    name: 'Agendadas',
    description: 'Sessões agendadas no mês',
    category: 'statistics',
    defaultWidth: 200,
    defaultHeight: 120,
  },
  {
    id: 'stat-unpaid',
    name: 'A Pagar',
    description: 'Sessões não pagas no mês',
    category: 'statistics',
    defaultWidth: 200,
    defaultHeight: 120,
  },
  {
    id: 'stat-nfse',
    name: 'NFSe Emitida',
    description: 'Sessões com NFSe emitida',
    category: 'statistics',
    defaultWidth: 200,
    defaultHeight: 120,
  },
  {
    id: 'stat-total-all',
    name: 'Total Geral',
    description: 'Todas as sessões registradas',
    category: 'statistics',
    defaultWidth: 200,
    defaultHeight: 120,
  },
  {
    id: 'stat-revenue-month',
    name: 'Faturamento do Mês',
    description: 'Valor total faturado no mês',
    category: 'statistics',
    defaultWidth: 200,
    defaultHeight: 120,
  },
  {
    id: 'stat-paid-month',
    name: 'Recebido no Mês',
    description: 'Valor recebido (pago) no mês',
    category: 'statistics',
    defaultWidth: 200,
    defaultHeight: 120,
  },
  {
    id: 'stat-missed-month',
    name: 'Faltas no Mês',
    description: 'Total de faltas no mês',
    category: 'statistics',
    defaultWidth: 200,
    defaultHeight: 120,
  },
  {
    id: 'stat-attendance-rate',
    name: 'Taxa de Comparecimento',
    description: 'Percentual de comparecimento',
    category: 'statistics',
    defaultWidth: 200,
    defaultHeight: 120,
  },
  {
    id: 'stat-unscheduled-month',
    name: 'Desmarcadas no Mês',
    description: 'Sessões desmarcadas no mês',
    category: 'statistics',
    defaultWidth: 200,
    defaultHeight: 120,
  },
];

export const AVAILABLE_FUNCTIONAL_CARDS: CardConfig[] = [
  {
    id: 'next-appointment',
    name: 'Próximo Agendamento',
    description: 'Detalhes da próxima sessão agendada',
    category: 'functional',
    defaultWidth: 350,
    defaultHeight: 220,
  },
  {
    id: 'contact-info',
    name: 'Informações de Contato',
    description: 'Telefone, email e endereço do paciente',
    category: 'functional',
    defaultWidth: 350,
    defaultHeight: 220,
  },
  {
    id: 'clinical-complaint',
    name: 'Queixa Clínica',
    description: 'Queixa clínica atual do paciente',
    category: 'functional',
    defaultWidth: 350,
    defaultHeight: 220,
  },
  {
    id: 'clinical-info',
    name: 'Informações Clínicas',
    description: 'Detalhes da terapia e modalidade',
    category: 'functional',
    defaultWidth: 700,
    defaultHeight: 280,
  },
  {
    id: 'history',
    name: 'Histórico de Alterações',
    description: 'Mudanças de horário e datas',
    category: 'functional',
    defaultWidth: 350,
    defaultHeight: 280,
  },
  {
    id: 'recent-notes',
    name: 'Últimas Notas Clínicas',
    description: 'Notas das sessões recentes',
    category: 'functional',
    defaultWidth: 350,
    defaultHeight: 300,
  },
  {
    id: 'quick-actions',
    name: 'Ações Rápidas',
    description: 'Botões para ações frequentes',
    category: 'functional',
    defaultWidth: 350,
    defaultHeight: 200,
  },
  {
    id: 'attendance-chart',
    name: 'Gráfico de Comparecimento',
    description: 'Visualização do histórico de presenças',
    category: 'functional',
    defaultWidth: 500,
    defaultHeight: 300,
  },
  {
    id: 'payment-summary',
    name: 'Resumo de Pagamentos',
    description: 'Status de pagamentos e pendências',
    category: 'functional',
    defaultWidth: 350,
    defaultHeight: 250,
  },
  {
    id: 'session-frequency',
    name: 'Frequência de Sessões',
    description: 'Análise de frequência e regularidade',
    category: 'functional',
    defaultWidth: 350,
    defaultHeight: 220,
  },
];

// Dashboard cards - for metrics section
export const AVAILABLE_DASHBOARD_CARDS: CardConfig[] = [
  {
    id: 'total-patients',
    name: 'Total de Pacientes',
    description: 'Número total de pacientes ativos no sistema',
    category: 'dashboard-cards',
    defaultWidth: 280,
    defaultHeight: 160,
  },
  {
    id: 'expected-revenue',
    name: 'Faturamento Esperado',
    description: 'Valor total esperado considerando todas as sessões agendadas',
    category: 'dashboard-cards',
    defaultWidth: 280,
    defaultHeight: 160,
  },
  {
    id: 'actual-revenue',
    name: 'Faturamento Real',
    description: 'Valor real das sessões que foram realizadas e pagas',
    category: 'dashboard-cards',
    defaultWidth: 280,
    defaultHeight: 160,
  },
  {
    id: 'attended-sessions',
    name: 'Sessões Comparecidas',
    description: 'Total de sessões realizadas com comparecimento confirmado',
    category: 'dashboard-cards',
    defaultWidth: 280,
    defaultHeight: 160,
  },
  {
    id: 'expected-sessions',
    name: 'Sessões Esperadas',
    description: 'Total de sessões agendadas incluindo futuras',
    category: 'dashboard-cards',
    defaultWidth: 280,
    defaultHeight: 160,
  },
  {
    id: 'missed-sessions',
    name: 'Faltas',
    description: 'Sessões marcadas como falta pelo paciente',
    category: 'dashboard-cards',
    defaultWidth: 280,
    defaultHeight: 160,
  },
  {
    id: 'pending-sessions',
    name: 'Sessões Pendentes',
    description: 'Sessões agendadas mas ainda não realizadas',
    category: 'dashboard-cards',
    defaultWidth: 280,
    defaultHeight: 160,
  },
  {
    id: 'unpaid-value',
    name: 'Valor a Receber',
    description: 'Total de valores de sessões realizadas mas ainda não pagas',
    category: 'dashboard-cards',
    defaultWidth: 280,
    defaultHeight: 160,
  },
  {
    id: 'active-therapists',
    name: 'Terapeutas Ativos',
    description: 'Número de terapeutas com sessões ativas no sistema',
    category: 'dashboard-cards',
    defaultWidth: 280,
    defaultHeight: 160,
  },
  {
    id: 'attendance-rate',
    name: 'Taxa de Comparecimento',
    description: 'Percentual de sessões comparecidas vs agendadas',
    category: 'dashboard-cards',
    defaultWidth: 280,
    defaultHeight: 160,
  },
  {
    id: 'monthly-growth',
    name: 'Crescimento Mensal',
    description: 'Comparação do faturamento com o mês anterior',
    category: 'dashboard-cards',
    defaultWidth: 280,
    defaultHeight: 160,
  },
  {
    id: 'payment-rate',
    name: 'Taxa de Pagamento',
    description: 'Percentual de sessões pagas vs sessões realizadas',
    category: 'dashboard-cards',
    defaultWidth: 280,
    defaultHeight: 160,
  },
];

// Dashboard charts - for visualization section
export const AVAILABLE_DASHBOARD_CHARTS: CardConfig[] = [
  {
    id: 'chart-revenue-trend',
    name: 'Tendência de Faturamento',
    description: 'Gráfico de linha mostrando evolução do faturamento ao longo do tempo',
    category: 'dashboard-charts',
    defaultWidth: 600,
    defaultHeight: 400,
  },
  {
    id: 'chart-session-types',
    name: 'Tipos de Sessão',
    description: 'Gráfico de pizza com distribuição de sessões comparecidas, faltas e cancelamentos',
    category: 'dashboard-charts',
    defaultWidth: 500,
    defaultHeight: 400,
  },
  {
    id: 'chart-therapist-distribution',
    name: 'Distribuição por Terapeuta',
    description: 'Gráfico de barras mostrando número de sessões por terapeuta',
    category: 'dashboard-charts',
    defaultWidth: 600,
    defaultHeight: 400,
  },
  {
    id: 'chart-monthly-comparison',
    name: 'Comparação Mensal',
    description: 'Gráfico de barras comparando métricas dos últimos 6 meses',
    category: 'dashboard-charts',
    defaultWidth: 700,
    defaultHeight: 400,
  },
  {
    id: 'chart-payment-status',
    name: 'Status de Pagamento',
    description: 'Gráfico de pizza mostrando proporção de sessões pagas vs não pagas',
    category: 'dashboard-charts',
    defaultWidth: 500,
    defaultHeight: 400,
  },
  {
    id: 'chart-attendance-weekly',
    name: 'Comparecimento Semanal',
    description: 'Gráfico de linha com taxa de comparecimento por semana',
    category: 'dashboard-charts',
    defaultWidth: 700,
    defaultHeight: 400,
  },
  {
    id: 'chart-revenue-by-therapist',
    name: 'Faturamento por Terapeuta',
    description: 'Gráfico de barras horizontais com faturamento individual de cada terapeuta',
    category: 'dashboard-charts',
    defaultWidth: 600,
    defaultHeight: 450,
  },
  {
    id: 'chart-patient-growth',
    name: 'Crescimento de Pacientes',
    description: 'Gráfico de área mostrando evolução do número de pacientes',
    category: 'dashboard-charts',
    defaultWidth: 700,
    defaultHeight: 400,
  },
  {
    id: 'chart-hourly-distribution',
    name: 'Distribuição por Horário',
    description: 'Gráfico de barras mostrando concentração de sessões por horário do dia',
    category: 'dashboard-charts',
    defaultWidth: 600,
    defaultHeight: 400,
  },
  {
    id: 'chart-cancellation-reasons',
    name: 'Motivos de Cancelamento',
    description: 'Gráfico de pizza com categorização dos motivos de faltas',
    category: 'dashboard-charts',
    defaultWidth: 500,
    defaultHeight: 400,
  },
];

export const ALL_AVAILABLE_CARDS = [...AVAILABLE_STAT_CARDS, ...AVAILABLE_FUNCTIONAL_CARDS, ...AVAILABLE_DASHBOARD_CARDS, ...AVAILABLE_DASHBOARD_CHARTS];
